chore: force to stop pipeline when next request in
linuxdeepin/dde-clipboard pull request #139
Opened 2023-06-28 05:41 UTC by Decodetalkers

sometimes the pipeline will be blocked, so here mv the pipeline read to QtCurrent runtime, when next request is in , close the pipeline

Log:

2023-06-30 06:57 UTC, justforlxz commented
/+1

2023-06-30 07:51 UTC, BLumia requested changes
日常批判 typo：

- `QtCurrent` > `QtConcurrent`
- `when next request is in ,` > `when next request is in,` （而且这个描述本身也有点 chinglish）

2023-06-30 07:51 UTC, BLumia commented on dde-clipboard-daemon/readpipedatatask.h
> +    // In some applications like chrome, when it sends data, seems kwin cannot handle the request good enough, sometimes also firefox
有具体的例子/情况说明吗？这个描述有点模糊，想了解下具体情况。

2023-07-06 11:05 UTC, BLumia approved these changes

2023-07-07 02:58 UTC, Decodetalkers commented
/merge

2023-07-07 02:58 UTC, merged