chore: remove try_compile
linuxdeepin/dde-clipboard pull request #140
Opened 2023-07-18 03:08 UTC by Decodetalkers

use option instead, and the try_compile is useless, never pass

Log:

2023-07-18 08:35 UTC, BLumia commented
我印象里是故意加的？ @justforlxz

2023-07-18 08:43 UTC, justforlxz commented
我记不太清宏处理的地方了，如果是DWayland的内容的话，应该可以直接改成依赖DWayland，就不用try compile了。

2023-07-19 09:36 UTC, Decodetalkers commented
@justforlxz 已经移除了原本的宏了

2023-07-21 02:33 UTC, justforlxz requested changes

2023-07-21 02:33 UTC, justforlxz commented on CMakeLists.txt
KF5Wayland 这一行注释可以删掉了。

2023-07-21 02:48 UTC, Decodetalkers commented on CMakeLists.txt
好了

2023-07-21 02:59 UTC, Decodetalkers commented
/check obs

2023-07-24 06:03 UTC, justforlxz approved these changes

2023-07-24 06:19 UTC, Decodetalkers commented
/merge

2023-07-24 06:20 UTC, merged