chore: service file
linuxdeepin/dde-clipboard pull request #142
Opened 2023-07-20 08:34 UTC by Decodetalkers

remove dde-clipboard-daemon.service to dbus service adjust Clipboard1 service

Log: service file adjust

2023-07-20 09:26 UTC, tsic404 commented
/check obs

2023-07-20 09:56 UTC, wineee requested changes

2023-07-20 09:56 UTC, wineee commented on misc/org.deepin.dde.daemon.Clipboard1.service.in
> +Name=org.deepin.dde.ClipboardLoader1
Why this file is same with `misc/org.deepin.dde.ClipboardLoader1.service.in`?

2023-07-20 10:03 UTC, Decodetalkers commented on misc/org.deepin.dde.daemon.Clipboard1.service.in
> +Name=org.deepin.dde.ClipboardLoader1
搞错了

2023-07-24 06:06 UTC, justforlxz commented on CMakeLists.txt
> +install(FILES ${CMAKE_CURRENT_BINARY_DIR}/dde-clipboard.service
创建软链即可

2023-08-02 09:13 UTC, justforlxz approved these changes

2023-08-02 09:15 UTC, Decodetalkers commented
/merge

2023-08-02 09:15 UTC, merged