chore: bump version
linuxdeepin/dde-clipboard pull request #153
Opened 2023-08-30 03:40 UTC by Decodetalkers

Log:

2023-08-30 03:42 UTC, Decodetalkers commented
https://github.com/linuxdeepin/developer-center/issues/4599
https://github.com/linuxdeepin/developer-center/issues/4718

2023-08-30 03:42 UTC, Decodetalkers commented
/integrate

2023-08-30 09:14 UTC, Decodetalkers commented
/integrate

2023-08-31 03:26 UTC, BLumia approved these changes

2023-08-31 03:26 UTC, BLumia requested changes

2023-08-31 03:26 UTC, BLumia commented on debian/changelog
> + -- chenhongtao <chenhongtao@deepin.org>  Wed, 20 Aug 2023 11:43:05 +0800
这个日期不对吧

2023-08-31 03:53 UTC, Decodetalkers commented on debian/changelog
> + -- chenhongtao <chenhongtao@deepin.org>  Wed, 20 Aug 2023 11:43:05 +0800
嗯，错了

2023-08-31 05:03 UTC, BLumia approved these changes

2023-08-31 05:09 UTC, Decodetalkers commented
/merge

2023-08-31 05:10 UTC, merged