fix: build failures under Qt 5.15
linuxdeepin/dde-clipboard pull request #2
Opened 2020-06-15 13:43 UTC by felixonmars

2020-06-27 06:33 UTC, xmuli submitted a review, later dismissed

2020-10-28 09:11 UTC, deepinAdmin approved these changes

2020-10-28 09:12 UTC, deepinAdmin requested changes
点错，忽略

2020-10-29 08:47 UTC, deepinAdmin approved these changes
Approve merged, Will be auto merge

2020-10-29 08:47 UTC, merged