Create README.md
linuxdeepin/dde-clipboard pull request #9
Opened 2022-03-24 02:18 UTC by Ronghzhe

2022-03-24 03:37 UTC, BLumia requested changes
获取帮助那里的列表是链接，只有文字的话是没多大帮助的。Getting help 下面的部分如果暂时不存在对应的链接的话可以去掉对应的项（比如 Gitter 和 IRC）。

另外 Commit Message 按照 [Wiki 里的提交信息规范](https://github.com/linuxdeepin/developer-center/wiki/Commit-%E6%8F%90%E4%BA%A4%E4%BF%A1%E6%81%AF%E8%A7%84%E8%8C%83) 改一下

2022-03-24 03:37 UTC, BLumia commented on README.md
> +    开发者代码贡献指南 (中文)
这些应当是链接

2022-03-24 03:37 UTC, BLumia commented on README.md
> +
过多的空行，一个空行就可以了

2022-03-26 05:51 UTC, BLumia commented on README.md
> +    开发者代码贡献指南 (中文)
这里应该是链接

2022-03-31 09:52 UTC, BLumia approved these changes
大致看上去可以了。不过要等到项目本身迁到 GitHub 后才能直接进行合并。可能要等一段时间。

顺便：到时候合并应该会 squash merge，commit message 可能会改掉。

2022-04-29 05:35 UTC, BLumia requested changes
还是需要按[提交信息规范](https://github.com/linuxdeepin/developer-center/wiki/Commit-%E6%8F%90%E4%BA%A4%E4%BF%A1%E6%81%AF%E8%A7%84%E8%8C%83)修改下 commit message 以便后续的合并。先整理一下此分支上的提交，squash 一下确保只剩一个 commit，然后修改这个 commit 的提交信息。

可供参考的格式：

```
chore: Create README.md

为 dde-clipboard 添加 README

Log: 为 dde-clipboard 添加 README
```

2022-05-20 05:06 UTC, BLumia approved these changes

2022-05-20 06:26 UTC, ssk-wh commented
已经可以合并了，回复'/ merge'可以自动合并，注意去掉/后面的空格

2022-05-20 06:37 UTC, Ronghzhe commented
/merge

2022-05-20 06:37 UTC, merged